@extends('layouts.app')

@section('content')
<section class="section">
    <div class="container">
        <p class="title">About YoBenny & Artaten</p>
        <p class="subtitle">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sollicitudin, quam ut sodales maximus, justo justo mollis nisi, a auctor enim nulla et massa. Nulla vitae lacinia dolor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus id dignissim lacus, non auctor odio. Phasellus eleifend sed mi vitae mattis. Ut venenatis malesuada nulla. Maecenas et interdum quam, vitae dictum tortor. Proin turpis neque, fermentum nec egestas sed, interdum at tellus. Nam metus nulla, varius sed scelerisque ac, ultricies vel turpis. Maecenas felis velit, elementum vitae maximus posuere, imperdiet in felis. Ut pulvinar, arcu ac vestibulum condimentum, mauris mi pulvinar odio, eu tincidunt orci nulla eget orci.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sollicitudin, quam ut sodales maximus, justo justo mollis nisi, a auctor enim nulla et massa. Nulla vitae lacinia dolor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus id dignissim lacus, non auctor odio. Phasellus eleifend sed mi vitae mattis. Ut venenatis malesuada nulla. Maecenas et interdum quam, vitae dictum tortor. Proin turpis neque, fermentum nec egestas sed, interdum at tellus. Nam metus nulla, varius sed scelerisque ac, ultricies vel turpis. Maecenas felis velit, elementum vitae maximus posuere, imperdiet in felis. Ut pulvinar, arcu ac vestibulum condimentum, mauris mi pulvinar odio, eu tincidunt orci nulla eget orci.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sollicitudin, quam ut sodales maximus, justo justo mollis nisi, a auctor enim nulla et massa. Nulla vitae lacinia dolor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus id dignissim lacus, non auctor odio. Phasellus eleifend sed mi vitae mattis. Ut venenatis malesuada nulla. Maecenas et interdum quam, vitae dictum tortor. Proin turpis neque, fermentum nec egestas sed, interdum at tellus. Nam metus nulla, varius sed scelerisque ac, ultricies vel turpis. Maecenas felis velit, elementum vitae maximus posuere, imperdiet in felis. Ut pulvinar, arcu ac vestibulum condimentum, mauris mi pulvinar odio, eu tincidunt orci nulla eget orci.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sollicitudin, quam ut sodales maximus, justo justo mollis nisi, a auctor enim nulla et massa. Nulla vitae lacinia dolor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus id dignissim lacus, non auctor odio. Phasellus eleifend sed mi vitae mattis. Ut venenatis malesuada nulla. Maecenas et interdum quam, vitae dictum tortor. Proin turpis neque, fermentum nec egestas sed, interdum at tellus. Nam metus nulla, varius sed scelerisque ac, ultricies vel turpis. Maecenas felis velit, elementum vitae maximus posuere, imperdiet in felis. Ut pulvinar, arcu ac vestibulum condimentum, mauris mi pulvinar odio, eu tincidunt orci nulla eget orci.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sollicitudin, quam ut sodales maximus, justo justo mollis nisi, a auctor enim nulla et massa. Nulla vitae lacinia dolor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus id dignissim lacus, non auctor odio. Phasellus eleifend sed mi vitae mattis. Ut venenatis malesuada nulla. Maecenas et interdum quam, vitae dictum tortor. Proin turpis neque, fermentum nec egestas sed, interdum at tellus. Nam metus nulla, varius sed scelerisque ac, ultricies vel turpis. Maecenas felis velit, elementum vitae maximus posuere, imperdiet in felis. Ut pulvinar, arcu ac vestibulum condimentum, mauris mi pulvinar odio, eu tincidunt orci nulla eget orci.</p>
    </div>
</section>
@endsection